name: ci-golang-workflow
on: [push]
jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: npm install go
      - run: go teste
      - run: go run math.go